ARDUINO_DIR  = /usr/share/arduino

TARGET       = CLItest
ARDUINO_LIBS = LiquidCrystal

MCU          = atmega1280
F_CPU        = 16000000
ARDUINO_PORT = /dev/cu.usb*

include /usr/share/arduino/Arduino.mk
